version: '3'

services:
  app:
    build: .
    ports:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/kotlin-hello"
      SPRING_DATASOURCE_USERNAME: "hello"
      SPRING_DATASOURCE_PASSWORD: "hello123"

  db:
    image: postgres:10-alpine
    volumes:
      - "./volumes/db/pg_data:/var/lib/postgresql/data" # host-relative-path:path-within-container
